trigger: none
pool:
  vmImage: 'ubuntu-20.04'
steps:
  - task: UseDotNet@2
    displayName: istalacja .NET 5
    inputs:
      packageType: 'sdk'
      version: '5.0.x'

  - task: DotNetCoreCLI@2
    displayName: Build all
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--no-restore'
  # - task: DotNetCoreCLI@2
  #   name: 'Publish'
  #   displayName: 'Publish'
  #   inputs:
  #     command: 'publish'
  #     publishWebProjects: false
  #     projects: '$(project)'
  #     arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  #     zipAfterPublish: false