 trigger: none
pool:
  vmImage: 'ubuntu-20.04'
steps:
  - task: UseDotNet@2
    displayName: istalacja .NET 5
    inputs:
      packageType: 'sdk'
      version: '5.0.x'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '.'