name: .NETapp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
    - name: Clean temp directory1
      run: rm -rf *
      working-directory: ./Booking.Server
    - name: Install dependencies
      run: dotnet restore
    - name: Clean temp directory2
      run: rm -rf *
      working-directory: ./Booking.Server/Booking.Server.API/
    - name: Build
      run: dotnet build
    - name: Test with the dotnet CLI
      run: dotnet test0.1
