name: dotnet build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Setup .NET 3.1.x
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: '3.1.x'
        - uses: actions/checkout@v3
        - name: Setup dotnet
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: '3.1.x'
        - name: Install dependencies
          run: dotnet add package Newtonsoft.Json --version 12.0.1
